server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com    // 服务端的实例名称
  client:
# 不向注册中心注册自己
    register-with-eureka: false
#标识自己就是注册中心，不需要检索服务
    fetch-registry: false
    service-url:
#设置与Eureka Servcer交互的地址查询服务和注册服务的地址
      defaultZone: http://eureka7002.com:7002/eureka/
#设置eureka自我保护机制，默认为开启（true），和时间（2s后不连接就删除其服务）
#  server:
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000

